### ISSUE TITLE
how to install ? stuck at step 6

### ISSUE THREAD

**Issue by SaiyajinK** [SpaceEnergy/SpaceTheme-Steam#1]
Hi,

I'm trying to install the theme for the new steam ui but I'm stuck at step 6

`6. Go back to Steam Settings, select Interface, and choose the SpaceTheme from the dropdown menu.`

the fact is that in the current steam beta there is no way to change the theme in the interface menu.

![interface](https://github.com/SpaceEnergy/SpaceTheme-Steam/assets/105972098/a34d1694-a53c-46f2-991d-242d59294139)

my steam version : 
![steamwebhelper_afUCte2IcY](https://github.com/SpaceEnergy/SpaceTheme-Steam/assets/105972098/25a8df0f-9b7c-431f-a5c5-af70ea0603d3)

did I miss something ? a video tutorial would not be refused. thanks

**Comment by Makezu90** [comment]
Try switch steam langauge english. I had same issue with other skin.

**Comment by SpaceEnergy** [comment]
Yes you have to set the Steam language to english otherwise you will not be displayed is due to the patcher that you installed in step 2 the creator of the patcher is working on it

**Comment by SaiyajinK** [comment]
Language change ok. That's now working great !
