### ISSUE TITLE
Update 1.0.4

### ISSUE THREAD

**Issue by thowtue** [SpaceEnergy/SpaceTheme-Steam#5]
Hey thanks for your quick hotfix for the class changes from the steam update,

For me it's still not working with 1.0.4, i'l tried to inject with SFP and millenium, and i have the default steam interface.

Fact: on my 1.0.3 install i have the scroll bar on my custom color still but it's the only custom color working after the steam update.

**Comment by SpaceEnergy** [comment]
Did you download the theme from GitHub manually and pack it into the skin folder or via the Community tab of Millennium?

**Comment by thowtue** [comment]
It was a manual install
here are the files :
![image](https://github.com/SpaceEnergy/SpaceTheme-Steam/assets/34699555/4f1ec74e-de48-450d-b670-531b02ab6edb)

**Comment by SpaceEnergy** [comment]
hmm ok then delete the theme folder and try to install it via the community hub from Millennium

**Comment by thowtue** [comment]
Ok my bad , i should had respected folder hierarchy as it was in the downloaded folder, i've put it like the SFP way so explains why it wasn't working, good now, thank's ! :)

**Comment by SpaceEnergy** [comment]
all right, then I'll close the issue
